-- Script para criar a tabela de prateleiras no Supabase
-- Execute este script no SQL Editor do seu projeto

CREATE TABLE IF NOT EXISTS public.prateleiras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    localizacao TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Habilitar RLS (Row Level Security) para segurança
ALTER TABLE public.prateleiras ENABLE ROW LEVEL SECURITY;

-- Criar política para permitir acesso total (leitura e escrita)
-- Nota: Em produção, você pode querer restringir isso apenas a usuários autenticados
CREATE POLICY "Acesso total a prateleiras" ON public.prateleiras
FOR ALL USING (true) WITH CHECK (true);