-- Script para corrigir a tabela de movimentações de estoque e suas relações
-- Execute este script no Editor SQL do Supabase

-- 1. Cria a tabela se ela ainda não existir
CREATE TABLE IF NOT EXISTS public.movimentacoes_estoque (
    id bigint generated by default as identity primary key,
    produto_id bigint,
    tipo_movimentacao text, -- 'ENTRADA', 'SAIDA', 'BATIMENTO'
    quantidade numeric,
    quantidade_anterior numeric,
    quantidade_nova numeric,
    usuario text,
    observacao text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Adiciona a Chave Estrangeira (Foreign Key) para permitir o JOIN com produtos
-- Isso corrige o erro 400 no carregamento do relatório
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'movimentacoes_estoque_produto_id_fkey' 
        AND table_name = 'movimentacoes_estoque'
    ) THEN
        ALTER TABLE public.movimentacoes_estoque
        ADD CONSTRAINT movimentacoes_estoque_produto_id_fkey
        FOREIGN KEY (produto_id)
        REFERENCES public.produtos(id)
        ON DELETE SET NULL;
    END IF;
END $$;

-- 3. Habilita segurança e políticas de acesso
ALTER TABLE public.movimentacoes_estoque ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso total a movimentacoes_estoque" ON public.movimentacoes_estoque FOR ALL USING (true) WITH CHECK (true);