-- Script de Correção: Recriar tabela movimentacoes_estoque com suporte a UUID
-- Execute no SQL Editor do Supabase

-- 1. Remove a tabela antiga (que está com o tipo errado na coluna produto_id)
DROP TABLE IF EXISTS public.movimentacoes_estoque;

-- 2. Cria a tabela novamente com produto_id como UUID
CREATE TABLE public.movimentacoes_estoque (
    id bigint generated by default as identity primary key,
    produto_id uuid, -- CORREÇÃO: Tipo UUID para compatibilidade com a tabela produtos
    tipo_movimentacao text,
    quantidade numeric,
    quantidade_anterior numeric,
    quantidade_nova numeric,
    usuario text,
    observacao text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Cria a chave estrangeira (agora deve funcionar sem erros)
ALTER TABLE public.movimentacoes_estoque
ADD CONSTRAINT movimentacoes_estoque_produto_id_fkey
FOREIGN KEY (produto_id)
REFERENCES public.produtos(id)
ON DELETE SET NULL;

-- 4. Re-aplica permissões
ALTER TABLE public.movimentacoes_estoque ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso total a movimentacoes_estoque" ON public.movimentacoes_estoque FOR ALL USING (true) WITH CHECK (true);