-- ==============================================================================
-- SCRIPT DE CRIAÇÃO E CONFIGURAÇÃO: TABELA COLETA_KM
-- ==============================================================================

-- 1. Criar a tabela se não existir
CREATE TABLE IF NOT EXISTS public.coleta_km (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    placa text not null,
    modelo text,
    km_anterior bigint,
    km_atual bigint not null,
    km_proxima_troca bigint,
    observacao text,
    data_coleta timestamp without time zone,
    usuario text
);

-- 2. Habilitar RLS (Segurança a Nível de Linha)
ALTER TABLE public.coleta_km ENABLE ROW LEVEL SECURITY;

-- 3. Limpar políticas antigas para evitar conflitos
DROP POLICY IF EXISTS "Permitir leitura coleta_km" ON public.coleta_km;
DROP POLICY IF EXISTS "Permitir insercao coleta_km" ON public.coleta_km;
DROP POLICY IF EXISTS "Permitir atualizacao coleta_km" ON public.coleta_km;
DROP POLICY IF EXISTS "Permitir exclusao coleta_km" ON public.coleta_km;

-- 4. Criar Políticas de Segurança (CRUD Completo para 'public/anon')
-- Ajuste conforme a necessidade de segurança do seu projeto.

-- Permitir SELECT (Ler histórico)
CREATE POLICY "Permitir leitura coleta_km"
ON public.coleta_km FOR SELECT
TO public
USING (true);

-- Permitir INSERT (Salvar nova coleta)
CREATE POLICY "Permitir insercao coleta_km"
ON public.coleta_km FOR INSERT
TO public
WITH CHECK (true);

-- Permitir UPDATE (Editar coleta existente)
CREATE POLICY "Permitir atualizacao coleta_km"
ON public.coleta_km FOR UPDATE
TO public
USING (true);

-- Permitir DELETE (Excluir coleta)
CREATE POLICY "Permitir exclusao coleta_km"
ON public.coleta_km FOR DELETE
TO public
USING (true);