-- Tabela de Postos
CREATE TABLE IF NOT EXISTS public.postos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filial text,
    razao_social text NOT NULL,
    cnpj text,
    cidade text,
    uf text,
    faturado boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de Abastecimento Externo
CREATE TABLE IF NOT EXISTS public.abastecimento_externo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    filial text,
    posto_id bigint REFERENCES public.postos(id),
    veiculo_placa text,
    tipo_veiculo text,
    km_atual numeric,
    km_anterior numeric,
    km_rodado numeric,
    litros numeric(10,2),
    valor_total numeric(10,2),
    valor_unitario numeric(10,3),
    rota text,
    usuario text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Garante que as colunas existam caso a tabela já tenha sido criada anteriormente
ALTER TABLE public.abastecimento_externo ADD COLUMN IF NOT EXISTS litros numeric(10,2);
ALTER TABLE public.abastecimento_externo ADD COLUMN IF NOT EXISTS valor_total numeric(10,2);
ALTER TABLE public.abastecimento_externo ADD COLUMN IF NOT EXISTS valor_unitario numeric(10,3);